version: '3.1'

services:
  postgres:
    image: postgres
    container_name: tastybook
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tastybook
      POSTGRES_USER: stevenyin
      POSTGRES_PASSWORD: stevenyin
    volumes:
      - type: bind
        source: C:\Users\Steven.Yin\tastybook_data
        target: /var/lib/postgresql/data
